site:
    title: 麻将
    serverUrl: ws://192.168.1.73:8010/g
application:
    message: Hello, Andy
spring:
    http:
        encoding:
            charset: UTF-8
            enabled: true
            force: true

logging:
    level:
        org:
            springframework:
                web: DEBUG
            hibernate: ERROR

debug:
    false


jdbc:
    url: jdbc:mysql://127.0.0.1:3306/boss?autoReconnect=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    maxNums: 20
    minNums: 5

weixin:
    appAppID: wx6cd6a382dde4b1b7
    appAppsecret: 745f685990920917b439f1ec237ca124
    appID: wx6cd6a382dde4b1b7
    appsecret: 745f685990920917b439f1ec237ca124
    clienttokenUrl: https://api.weixin.qq.com/cgi-bin/token
    jsticketUrl: https://api.weixin.qq.com/cgi-bin/ticket/getticket
    authorizeUrl: https://open.weixin.qq.com/connect/oauth2/authorize
    tokenUrl: https://api.weixin.qq.com/sns/oauth2/access_token
    refresstokenUrl: https://api.weixin.qq.com/sns/oauth2/refresh_token
    getuserUrl: https://api.weixin.qq.com/sns/userinfo

    siteUrl: http://127.0.0.1:8080
#    siteUrl: http://www.bjmajiang.com

alipay:
  app_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlc2MTUuMJm8FdJFpUgdH5RIQj5DD+wLkBkt/y7XUJuxObbOIWPkRbyx1DLIoTNWpvTGzM6lzoKvncwjETnmo+O9A9SGfesDJvCB7mEBkNDI1w6OkF2EEy5uXSGFjNU/HRxMgonjkav2Moo4lCQjUSr7xz2kwVPeSiJYqZO6Jqwg5BDN9nDmR1oQOVz/Lfp5ejmEwXv6PedDKYkGHlSWUCdM1kf0Jc+mPWulSWTzsAgf1sdMpCCRD4lgMU+39ku/GiEACUt3I/esrqN/ymx65UQYKSjIQc4yLUPqyq0A239X0FzRla7atmIn8+F/6hTMepeGd9PXOCW9pCF7HlEi+wwIDAQAB

boss:
    address: 127.0.0.1
    port: 11002
    publicKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCOLX6y_Ud7svHi4PDOUgQMhn9DrWjTU7che_8KOK0XoItY8NlAhVXdus82Xvs268O-GgmeVmOGwXfxrFgft5CCQx-okQM2_qbuKWH1IA3JRYbKz2Kt93wtHZHqSFmwtIcv3kxupbw9umqP8dBjsPUue9vHcbem3uys6e56FHvjowIDAQAB